
format = """
$username\
$directory\
$git_branch\
$git_status\
$line_break\
$character"""


command_timeout = 1000


[username]
style_user = "yellow bold"
show_always = true
format = "[$user]($style)"


[directory]
style = "blue bold"
format = " in [$path]($style)"
truncation_length = 3
truncation_symbol = "…/"


[git_branch]
symbol = "❖ "
style = "white bold"

format = " on [$symbol$branch]($style)"


[character]
success_symbol = "[❯](green bold)"
error_symbol = "[❯](red bold)"